apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: simple-event-subscriber
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: simple-event-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-listener-service
