apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: simple-event-channel
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory
