apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-listener-service
spec:
  template:
    metadata:
      name: event-listener-service-v1
    spec:
      containers:
      - image: mkarakas/simple-rest

