
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: simple
  namespace: default
spec:
  template:
    metadata:
      name: simple-v1
    spec:
      containers:
        # Replace {username} with your actual DockerHub
        - image: docker.io/mkarakas/simple-rest
          env:
            - name: VERSION
              value: "V1"
  traffic:
  - tag: current
    revisionName: simple-v1
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0