apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: cj-event-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Hello"}'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: simple-sink-service